name: zeko_hotel_crm
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  get_it: ^7.7.0
  dartz: ^0.10.1

  # Local Storage
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

  # Networking
  http: ^1.2.2

  # Language Support
  flutter_localizations:
    sdk: flutter
  intl: any

  # UI
  skeletonizer: ^1.4.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  flutter_dropdown_alert: ^1.0.7
  logger: ^2.4.0
  scaled_app: ^2.3.0
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.0
  fluttericon: ^2.0.0
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flutter_date_range_picker: ^0.1.1
  auto_size_text: ^3.0.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/platform/
    - assets/lottie/
    - assets/icons/
    - assets/country-code-with-flag.json